package com.tlan.common.model;

// Generated 2014-5-16 11:14:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WxModuleContentNewcarReserve generated by hbm2java
 */
@Entity
@Table(name = "wx_module_content_newcar_reserve")
public class WxModuleContentNewcarReserve implements java.io.Serializable {

	private Integer id;
	private String openid;
	private String gzhHash;
	private String reserveTime;
	private String userName;
	private String userMobile;
	private String carModel;
	private String carConf;
	private String userProvince;
	private String userCity;
	private String dealerCode;
	private String dealerName;
	private String deleteFlag;
	private String createTime;
	private String dealerAddress;
	private String remark;

	public WxModuleContentNewcarReserve() {
	}

	public WxModuleContentNewcarReserve(String openid, String gzhHash,
			String reserveTime, String userName, String userMobile,
			String carModel, String carConf, String userProvince,
			String userCity, String dealerCode, String dealerName,
			String deleteFlag, String createTime, String dealerAddress,
			String remark) {
		this.openid = openid;
		this.gzhHash = gzhHash;
		this.reserveTime = reserveTime;
		this.userName = userName;
		this.userMobile = userMobile;
		this.carModel = carModel;
		this.carConf = carConf;
		this.userProvince = userProvince;
		this.userCity = userCity;
		this.dealerCode = dealerCode;
		this.dealerName = dealerName;
		this.deleteFlag = deleteFlag;
		this.createTime = createTime;
		this.dealerAddress = dealerAddress;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "openid", length = 50)
	public String getOpenid() {
		return this.openid;
	}

	public void setOpenid(String openid) {
		this.openid = openid;
	}

	@Column(name = "gzh_hash", length = 36)
	public String getGzhHash() {
		return this.gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "reserve_time", length = 25)
	public String getReserveTime() {
		return this.reserveTime;
	}

	public void setReserveTime(String reserveTime) {
		this.reserveTime = reserveTime;
	}

	@Column(name = "user_name", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_mobile", length = 20)
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "car_model", length = 20)
	public String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	@Column(name = "car_conf", length = 20)
	public String getCarConf() {
		return this.carConf;
	}

	public void setCarConf(String carConf) {
		this.carConf = carConf;
	}

	@Column(name = "user_province", length = 20)
	public String getUserProvince() {
		return this.userProvince;
	}

	public void setUserProvince(String userProvince) {
		this.userProvince = userProvince;
	}

	@Column(name = "user_city", length = 30)
	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	@Column(name = "dealer_code", length = 5)
	public String getDealerCode() {
		return this.dealerCode;
	}

	public void setDealerCode(String dealerCode) {
		this.dealerCode = dealerCode;
	}

	@Column(name = "dealer_name", length = 50)
	public String getDealerName() {
		return this.dealerName;
	}

	public void setDealerName(String dealerName) {
		this.dealerName = dealerName;
	}

	@Column(name = "delete_flag", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "create_time", length = 20)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "dealer_address", length = 200)
	public String getdealerAddress() {
		return this.dealerAddress;
	}

	public void setdealerAddress(String dealerAddress) {
		this.dealerAddress = dealerAddress;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
