package com.tlan.common.model.creditactive;

// Generated 2014-6-18 14:02:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
/**
 * WxCreditEnrollView generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_credit_enroll_view")
public class WxCreditEnrollView implements java.io.Serializable {

	private String wxMemberCreditEnrollGuid;
	private String memberCreditGuid;
	private String itemName;
	private String itemNotice;
	private Integer itemSort;

	public WxCreditEnrollView() {
	}

	public WxCreditEnrollView(String wxMemberCreditEnrollGuid) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
	}

	public WxCreditEnrollView(String wxMemberCreditEnrollGuid,String memberCreditGuid, String itemName,
			String itemNotice, Integer itemSort) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
		this.memberCreditGuid = memberCreditGuid;
		this.itemName = itemName;
		this.itemNotice = itemNotice;
		this.itemSort = itemSort;
	}
	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "wx_member_credit_enroll_guid", nullable = false, length = 36)
	public String getWxMemberCreditEnrollGuid() {
		return this.wxMemberCreditEnrollGuid;
	}

	public void setWxMemberCreditEnrollGuid(String wxMemberCreditEnrollGuid) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
	}
	@Column(name = "member_credit_guid", nullable = false, length = 36)
	public String getMemberCreditGuid() {
		return this.memberCreditGuid;
	}

	public void setMemberCreditGuid(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	@Column(name = "item_name", length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_notice")
	public String getItemNotice() {
		return this.itemNotice;
	}

	public void setItemNotice(String itemNotice) {
		this.itemNotice = itemNotice;
	}

	@Column(name = "item_sort")
	public Integer getItemSort() {
		return this.itemSort;
	}

	public void setItemSort(Integer itemSort) {
		this.itemSort = itemSort;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WxCreditEnrollView))
			return false;
		WxCreditEnrollView castOther = (WxCreditEnrollView) other;

		return ((this.getWxMemberCreditEnrollGuid() == castOther.getWxMemberCreditEnrollGuid()) || (this
				.getWxMemberCreditEnrollGuid() != null
				&& castOther.getWxMemberCreditEnrollGuid() != null && this
				.getWxMemberCreditEnrollGuid().equals(castOther.getWxMemberCreditEnrollGuid())))
				&& ((this.getMemberCreditGuid() == castOther.getMemberCreditGuid()) || (this
				.getMemberCreditGuid() != null
				&& castOther.getMemberCreditGuid() != null && this
				.getMemberCreditGuid().equals(castOther.getMemberCreditGuid())))
				&& ((this.getItemName() == castOther.getItemName()) || (this
						.getItemName() != null
						&& castOther.getItemName() != null && this
						.getItemName().equals(castOther.getItemName())))
				&& ((this.getItemNotice() == castOther.getItemNotice()) || (this
						.getItemNotice() != null
						&& castOther.getItemNotice() != null && this
						.getItemNotice().equals(castOther.getItemNotice())))
				&& ((this.getItemSort() == castOther.getItemSort()) || (this
						.getItemSort() != null
						&& castOther.getItemSort() != null && this
						.getItemSort().equals(castOther.getItemSort())));
	}

	public int hashCode() {
		int result = 17;
		
		result = 37
				* result
				+ (getWxMemberCreditEnrollGuid() == null ? 0 : this
						.getWxMemberCreditEnrollGuid().hashCode());

		result = 37
				* result
				+ (getMemberCreditGuid() == null ? 0 : this
						.getMemberCreditGuid().hashCode());
		result = 37 * result
				+ (getItemName() == null ? 0 : this.getItemName().hashCode());
		result = 37
				* result
				+ (getItemNotice() == null ? 0 : this.getItemNotice()
						.hashCode());
		result = 37 * result
				+ (getItemSort() == null ? 0 : this.getItemSort().hashCode());
		return result;
	}

}
