package com.tlan.common.model.creditactive;

// Generated 2014-6-18 11:42:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Embeddable;

import org.hibernate.annotations.GenericGenerator;
/**
 * WxCreditActiveViewId generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_credit_active_view")
public class WxCreditActiveView implements java.io.Serializable {

	private String memberActGuid;
	private String memberCreditGuid;
	private String memberGuid;
	private String openId;
	private String userName;
	private String gzhHash;
	private String actName;
	private String startOn;
	private String endOn;
	private String createdOn;
	private Integer actCredit;

	public WxCreditActiveView() {
	}

	public WxCreditActiveView(String memberActGuid, String memberCreditGuid,
			String memberGuid) {
		this.memberActGuid = memberActGuid;
		this.memberCreditGuid = memberCreditGuid;
		this.memberGuid = memberGuid;
	}

	public WxCreditActiveView(String memberActGuid, String memberCreditGuid,
			String memberGuid, String openId, String userName, String gzhHash,
			String actName, String startOn, String endOn, String createdOn,
			Integer actCredit) {
		this.memberActGuid = memberActGuid;
		this.memberCreditGuid = memberCreditGuid;
		this.memberGuid = memberGuid;
		this.openId = openId;
		this.userName = userName;
		this.gzhHash = gzhHash;
		this.actName = actName;
		this.startOn = startOn;
		this.endOn = endOn;
		this.createdOn = createdOn;
		this.actCredit = actCredit;
	}

	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "member_act_guid", unique = true, nullable = false, insertable = true, updatable = true, length = 36)
	public String getMemberActGuid() {
		return this.memberActGuid;
	}

	public void setMemberActGuid(String memberActGuid) {
		this.memberActGuid = memberActGuid;
	}

	@Column(name = "member_credit_guid", unique = true, nullable = false, insertable = true, updatable = true, length = 36)
	public String getMemberCreditGuid() {
		return this.memberCreditGuid;
	}

	public void setMemberCreditGuid(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	@Column(name = "member_guid", unique = true, nullable = false, insertable = true, updatable = true, length = 36)
	public String getMemberGuid() {
		return this.memberGuid;
	}

	public void setMemberGuid(String memberGuid) {
		this.memberGuid = memberGuid;
	}


	@Column(name = "open_id", unique = true, nullable = false, insertable = true, updatable = true, length = 50)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "user_name", unique = true, nullable = false, insertable = true, updatable = true, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "gzh_hash", unique = true, nullable = false, insertable = true, updatable = true, length = 36)
	public String getGzhHash() {
		return this.gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "act_name", unique = true, nullable = false, insertable = true, updatable = true, length = 100)
	public String getActName() {
		return this.actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}


	@Column(name = "start_on", unique = true, nullable = false, insertable = true, updatable = true, length = 25)
	public String getStartOn() {
		return this.startOn;
	}

	public void setStartOn(String startOn) {
		this.startOn = startOn;
	}

	@Column(name = "end_on", unique = true, nullable = false, insertable = true, updatable = true, length = 25)
	public String getEndOn() {
		return this.endOn;
	}

	public void setEndOn(String endOn) {
		this.endOn = endOn;
	}

	@Column(name = "created_on", unique = true, nullable = false, insertable = true, updatable = true, length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "act_credit", unique = true, nullable = false, insertable = true, updatable = true, length = 50  )
	public Integer getActCredit() {
		return this.actCredit;
	}

	public void setActCredit(Integer actCredit) {
		this.actCredit = actCredit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WxCreditActiveView))
			return false;
		WxCreditActiveView castOther = (WxCreditActiveView) other;

		return ((this.getMemberActGuid() == castOther.getMemberActGuid()) || (this
				.getMemberActGuid() != null
				&& castOther.getMemberActGuid() != null && this
				.getMemberActGuid().equals(castOther.getMemberActGuid())))
				&& ((this.getMemberCreditGuid() == castOther
						.getMemberCreditGuid()) || (this.getMemberCreditGuid() != null
						&& castOther.getMemberCreditGuid() != null && this
						.getMemberCreditGuid().equals(
								castOther.getMemberCreditGuid())))
				&& ((this.getMemberGuid() == castOther.getMemberGuid()) || (this
						.getMemberGuid() != null
						&& castOther.getMemberGuid() != null && this
						.getMemberGuid().equals(castOther.getMemberGuid())))
				&& ((this.getOpenId() == castOther.getOpenId()) || (this
						.getOpenId() != null && castOther.getOpenId() != null && this
						.getOpenId().equals(castOther.getOpenId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getGzhHash() == castOther.getGzhHash()) || (this
						.getGzhHash() != null && castOther.getGzhHash() != null && this
						.getGzhHash().equals(castOther.getGzhHash())))
				&& ((this.getActName() == castOther.getActName()) || (this
						.getActName() != null && castOther.getActName() != null && this
						.getActName().equals(castOther.getActName())))
				&& ((this.getStartOn() == castOther.getStartOn()) || (this
						.getStartOn() != null && castOther.getStartOn() != null && this
						.getStartOn().equals(castOther.getStartOn())))
				&& ((this.getEndOn() == castOther.getEndOn()) || (this
						.getEndOn() != null && castOther.getEndOn() != null && this
						.getEndOn().equals(castOther.getEndOn())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this
						.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this
						.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getActCredit() == castOther.getActCredit()) || (this
						.getActCredit() != null
						&& castOther.getActCredit() != null && this
						.getActCredit().equals(castOther.getActCredit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMemberActGuid() == null ? 0 : this.getMemberActGuid()
						.hashCode());
		result = 37
				* result
				+ (getMemberCreditGuid() == null ? 0 : this
						.getMemberCreditGuid().hashCode());
		result = 37
				* result
				+ (getMemberGuid() == null ? 0 : this.getMemberGuid()
						.hashCode());
		result = 37 * result
				+ (getOpenId() == null ? 0 : this.getOpenId().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getGzhHash() == null ? 0 : this.getGzhHash().hashCode());
		result = 37 * result
				+ (getActName() == null ? 0 : this.getActName().hashCode());
		result = 37 * result
				+ (getStartOn() == null ? 0 : this.getStartOn().hashCode());
		result = 37 * result
				+ (getEndOn() == null ? 0 : this.getEndOn().hashCode());
		result = 37 * result
				+ (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result
				+ (getActCredit() == null ? 0 : this.getActCredit().hashCode());
		return result;
	}

}
