package  com.tlan.common.model.creditactive;

// Generated 2014-6-18 14:02:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxMemberCreditManageView generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_member_credit_manage_view")
public class WxMemberCreditManageView implements java.io.Serializable {

	private String memberActGuid;
	private String memberCreditGuid;
	private String actName;
	private String userName;
	private String nickName;
	private String userTel;
	private String createdOn;
	private String t1;
	private String t2;
	private String t3;
	private String t4;
	private String t5;
	private String t6;
	private String t7;
	private String t8;
	private String t9;
	private String t10;

	public WxMemberCreditManageView() {
	}

	public WxMemberCreditManageView(String memberActGuid) {
		this.memberActGuid = memberActGuid;
	}

	public WxMemberCreditManageView(String memberActGuid,String memberCreditGuid, String actName,
			String userName, String nickName, String userTel, String createdOn,
			String t1, String t2, String t3, String t4, String t5, String t6,
			String t7, String t8, String t9, String t10) {
		this.memberActGuid = memberActGuid;
		this.memberCreditGuid = memberCreditGuid;
		this.actName = actName;
		this.userName = userName;
		this.nickName = nickName;
		this.userTel = userTel;
		this.createdOn = createdOn;
		this.t1 = t1;
		this.t2 = t2;
		this.t3 = t3;
		this.t4 = t4;
		this.t5 = t5;
		this.t6 = t6;
		this.t7 = t7;
		this.t8 = t8;
		this.t9 = t9;
		this.t10 = t10;
	}
	
	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "member_act_guid", nullable = false, length = 36)
	public String getMemberActGuid() {
		return this.memberActGuid;
	}

	public void setMemberActGuid(String memberActGuid) {
		this.memberActGuid = memberActGuid;
	}
	
	@Column(name = "member_credit_guid", nullable = false, length = 36)
	public String getMemberCreditGuid() {
		return this.memberCreditGuid;
	}

	public void setMemberCreditGuid(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	@Column(name = "act_name", length = 100)
	public String getActName() {
		return this.actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}

	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "nick_name", length = 100)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "user_tel", length = 25)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "t1")
	public String getT1() {
		return this.t1;
	}

	public void setT1(String t1) {
		this.t1 = t1;
	}

	@Column(name = "t2")
	public String getT2() {
		return this.t2;
	}

	public void setT2(String t2) {
		this.t2 = t2;
	}

	@Column(name = "t3")
	public String getT3() {
		return this.t3;
	}

	public void setT3(String t3) {
		this.t3 = t3;
	}

	@Column(name = "t4")
	public String getT4() {
		return this.t4;
	}

	public void setT4(String t4) {
		this.t4 = t4;
	}

	@Column(name = "t5")
	public String getT5() {
		return this.t5;
	}

	public void setT5(String t5) {
		this.t5 = t5;
	}

	@Column(name = "t6")
	public String getT6() {
		return this.t6;
	}

	public void setT6(String t6) {
		this.t6 = t6;
	}

	@Column(name = "t7")
	public String getT7() {
		return this.t7;
	}

	public void setT7(String t7) {
		this.t7 = t7;
	}

	@Column(name = "t8")
	public String getT8() {
		return this.t8;
	}

	public void setT8(String t8) {
		this.t8 = t8;
	}

	@Column(name = "t9")
	public String getT9() {
		return this.t9;
	}

	public void setT9(String t9) {
		this.t9 = t9;
	}

	@Column(name = "t10")
	public String getT10() {
		return this.t10;
	}

	public void setT10(String t10) {
		this.t10 = t10;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WxMemberCreditManageView))
			return false;
		WxMemberCreditManageView castOther = (WxMemberCreditManageView) other;

		return ((this.getMemberActGuid() == castOther.getMemberActGuid()) || (this
				.getMemberActGuid() != null
				&& castOther.getMemberActGuid() != null && this
				.getMemberActGuid().equals(castOther.getMemberActGuid())))
				&& ((this.getMemberCreditGuid() == castOther.getMemberCreditGuid()) || (this
				.getMemberCreditGuid() != null
				&& castOther.getMemberCreditGuid() != null && this
				.getMemberCreditGuid().equals(castOther.getMemberCreditGuid())))
				&& ((this.getActName() == castOther.getActName()) || (this
						.getActName() != null && castOther.getActName() != null && this
						.getActName().equals(castOther.getActName())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getNickName() == castOther.getNickName()) || (this
						.getNickName() != null
						&& castOther.getNickName() != null && this
						.getNickName().equals(castOther.getNickName())))
				&& ((this.getUserTel() == castOther.getUserTel()) || (this
						.getUserTel() != null && castOther.getUserTel() != null && this
						.getUserTel().equals(castOther.getUserTel())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this
						.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this
						.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getT1() == castOther.getT1()) || (this.getT1() != null
						&& castOther.getT1() != null && this.getT1().equals(
						castOther.getT1())))
				&& ((this.getT2() == castOther.getT2()) || (this.getT2() != null
						&& castOther.getT2() != null && this.getT2().equals(
						castOther.getT2())))
				&& ((this.getT3() == castOther.getT3()) || (this.getT3() != null
						&& castOther.getT3() != null && this.getT3().equals(
						castOther.getT3())))
				&& ((this.getT4() == castOther.getT4()) || (this.getT4() != null
						&& castOther.getT4() != null && this.getT4().equals(
						castOther.getT4())))
				&& ((this.getT5() == castOther.getT5()) || (this.getT5() != null
						&& castOther.getT5() != null && this.getT5().equals(
						castOther.getT5())))
				&& ((this.getT6() == castOther.getT6()) || (this.getT6() != null
						&& castOther.getT6() != null && this.getT6().equals(
						castOther.getT6())))
				&& ((this.getT7() == castOther.getT7()) || (this.getT7() != null
						&& castOther.getT7() != null && this.getT7().equals(
						castOther.getT7())))
				&& ((this.getT8() == castOther.getT8()) || (this.getT8() != null
						&& castOther.getT8() != null && this.getT8().equals(
						castOther.getT8())))
				&& ((this.getT9() == castOther.getT9()) || (this.getT9() != null
						&& castOther.getT9() != null && this.getT9().equals(
						castOther.getT9())))
				&& ((this.getT10() == castOther.getT10()) || (this.getT10() != null
						&& castOther.getT10() != null && this.getT10().equals(
						castOther.getT10())));
	}

	public int hashCode() {
		int result = 17;
		
		result = 37
				* result
				+ (getMemberActGuid() == null ? 0 : this
						.getMemberActGuid().hashCode());
		result = 37
				* result
				+ (getMemberCreditGuid() == null ? 0 : this
						.getMemberCreditGuid().hashCode());
		result = 37 * result
				+ (getActName() == null ? 0 : this.getActName().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getNickName() == null ? 0 : this.getNickName().hashCode());
		result = 37 * result
				+ (getUserTel() == null ? 0 : this.getUserTel().hashCode());
		result = 37 * result
				+ (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getT1() == null ? 0 : this.getT1().hashCode());
		result = 37 * result + (getT2() == null ? 0 : this.getT2().hashCode());
		result = 37 * result + (getT3() == null ? 0 : this.getT3().hashCode());
		result = 37 * result + (getT4() == null ? 0 : this.getT4().hashCode());
		result = 37 * result + (getT5() == null ? 0 : this.getT5().hashCode());
		result = 37 * result + (getT6() == null ? 0 : this.getT6().hashCode());
		result = 37 * result + (getT7() == null ? 0 : this.getT7().hashCode());
		result = 37 * result + (getT8() == null ? 0 : this.getT8().hashCode());
		result = 37 * result + (getT9() == null ? 0 : this.getT9().hashCode());
		result = 37 * result
				+ (getT10() == null ? 0 : this.getT10().hashCode());
		return result;
	}

}
