package com.tlan.common.model.creditactive;

// Generated 2014-6-16 17:08:28 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxMemberCreditActiveViewId generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_member_credit_active_view")
public class WxMemberCreditActiveView implements java.io.Serializable {

	private String openId;
	private String userGuid;
	private String gzhName;
	private String gzhHash;
	private String userName;
	private String userSex;
	private String userTel;
	private String nickName;
	private String createdOn;
	private Integer status;
	private Integer memberLevel;
	private String memberNo;
	private String user2carGuid;
	private String registerTime;
	private String registerFrom;
	private String followedFrom;
	private String headimgurl;
	private String city;
	private String province;
	private String country;
	private Integer currentCredit;
	private Integer countCredit;

	public WxMemberCreditActiveView() {
	}

	public WxMemberCreditActiveView(String userGuid) {
		this.userGuid = userGuid;
	}
	
	public WxMemberCreditActiveView(String openId, String userGuid,
			String gzhName, String gzhHash, String userName, String userSex,
			String userTel, String nickName, String createdOn, Integer status,
			Integer memberLevel, String memberNo, String user2carGuid,
			String registerTime, String registerFrom, String followedFrom,
			String headimgurl, String city, String province, String country,
			Integer countCredit) {
		super();
		this.openId = openId;
		this.userGuid = userGuid;
		this.gzhName = gzhName;
		this.gzhHash = gzhHash;
		this.userName = userName;
		this.userSex = userSex;
		this.userTel = userTel;
		this.nickName = nickName;
		this.createdOn = createdOn;
		this.status = status;
		this.memberLevel = memberLevel;
		this.memberNo = memberNo;
		this.user2carGuid = user2carGuid;
		this.registerTime = registerTime;
		this.registerFrom = registerFrom;
		this.followedFrom = followedFrom;
		this.headimgurl = headimgurl;
		this.city = city;
		this.province = province;
		this.country = country;
		this.countCredit = countCredit;
	}

	
	@Column(name = "open_id", length = 50)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "user_guid", nullable = false, length = 36)
	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	@Column(name = "gzh_name", length = 30)
	public String getGzhName() {
		return this.gzhName;
	}

	public void setGzhName(String gzhName) {
		this.gzhName = gzhName;
	}
	
	@Column(name = "user_name", length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "gzh_hash",length = 30)
	public String getGzhHash() {
		return gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "user_sex", length = 20)
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "user_tel", length = 25)
	public String getUserTel() {
		return this.userTel;
	}

	public void setUserTel(String userTel) {
		this.userTel = userTel;
	}

	@Column(name = "nick_name", length = 100)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "member_level")
	public Integer getMemberLevel() {
		return this.memberLevel;
	}

	public void setMemberLevel(Integer memberLevel) {
		this.memberLevel = memberLevel;
	}

	@Column(name = "member_no", length = 50)
	public String getMemberNo() {
		return this.memberNo;
	}

	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo;
	}

	@Column(name = "user2car_guid", length = 36)
	public String getUser2carGuid() {
		return this.user2carGuid;
	}

	public void setUser2carGuid(String user2carGuid) {
		this.user2carGuid = user2carGuid;
	}

	@Column(name = "register_time", length = 25)
	public String getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(String registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "register_from", length = 100)
	public String getRegisterFrom() {
		return this.registerFrom;
	}

	public void setRegisterFrom(String registerFrom) {
		this.registerFrom = registerFrom;
	}

	@Column(name = "followed_from", length = 100)
	public String getFollowedFrom() {
		return this.followedFrom;
	}

	public void setFollowedFrom(String followedFrom) {
		this.followedFrom = followedFrom;
	}

	@Column(name = "headimgurl")
	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

	@Column(name = "city", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "province", length = 100)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "current_credit")
	public Integer getCurrentCredit() {
		return currentCredit;
	}

	public void setCurrentCredit(Integer currentCredit) {
		this.currentCredit = currentCredit;
	}

	@Column(name = "count_credit", precision = 32, scale = 0)
	public Integer getCountCredit() {
		return this.countCredit;
	}

	public void setCountCredit(Integer countCredit) {
		this.countCredit = countCredit;
	}

}
