package  com.tlan.common.model.creditactive;

// Generated 2014-6-16 17:08:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WxMemberCreditEnrollF generated by hbm2java
 */
@Entity
@Table(name = "wx_member_credit_enroll_f")
public class WxMemberCreditEnrollF implements java.io.Serializable {

	private String wxMemberCreditEnrollGuid;
	private String memberCreditGuid;
	private String itemName;
	private String itemNotice;
	private Integer itemSort;
	private Integer requiredItem;
	private String createdBy;
	private String createdOn;
	private String modifyBy;
	private String modifyOn;
	private String publishOn;
	private String publishBy;
	private Integer delFlag;
	private Integer updateCount;

	public WxMemberCreditEnrollF() {
	}

	public WxMemberCreditEnrollF(String wxMemberCreditEnrollGuid) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
	}

	public WxMemberCreditEnrollF(String wxMemberCreditEnrollGuid,
			String memberCreditGuid, String itemName, String itemNotice,
			Integer itemSort, Integer requiredItem, String createdBy,
			String createdOn, String modifyBy, String modifyOn,
			String publishOn, String publishBy, Integer delFlag,
			Integer updateCount) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
		this.memberCreditGuid = memberCreditGuid;
		this.itemName = itemName;
		this.itemNotice = itemNotice;
		this.itemSort = itemSort;
		this.requiredItem = requiredItem;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.publishOn = publishOn;
		this.publishBy = publishBy;
		this.delFlag = delFlag;
		this.updateCount = updateCount;
	}

	@Id
	@Column(name = "wx_member_credit_enroll_guid", unique = true, nullable = false, length = 36)
	public String getWxMemberCreditEnrollGuid() {
		return this.wxMemberCreditEnrollGuid;
	}

	public void setWxMemberCreditEnrollGuid(String wxMemberCreditEnrollGuid) {
		this.wxMemberCreditEnrollGuid = wxMemberCreditEnrollGuid;
	}

	@Column(name = "member_credit_guid", length = 36)
	public String getMemberCreditGuid() {
		return this.memberCreditGuid;
	}

	public void setMemberCreditGuid(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	@Column(name = "item_name", length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_notice")
	public String getItemNotice() {
		return this.itemNotice;
	}

	public void setItemNotice(String itemNotice) {
		this.itemNotice = itemNotice;
	}

	@Column(name = "item_sort")
	public Integer getItemSort() {
		return this.itemSort;
	}

	public void setItemSort(Integer itemSort) {
		this.itemSort = itemSort;
	}

	@Column(name = "required_item")
	public Integer getRequiredItem() {
		return this.requiredItem;
	}

	public void setRequiredItem(Integer requiredItem) {
		this.requiredItem = requiredItem;
	}

	@Column(name = "created_by", length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by", length = 36)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modify_on", length = 25)
	public String getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(String modifyOn) {
		this.modifyOn = modifyOn;
	}

	@Column(name = "publish_on", length = 25)
	public String getPublishOn() {
		return this.publishOn;
	}

	public void setPublishOn(String publishOn) {
		this.publishOn = publishOn;
	}

	@Column(name = "publish_by", length = 36)
	public String getPublishBy() {
		return this.publishBy;
	}

	public void setPublishBy(String publishBy) {
		this.publishBy = publishBy;
	}

	@Column(name = "del_flag")
	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "update_count")
	public Integer getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

}
