package com.tlan.common.model.creditactive;

// Generated 2014-7-8 9:42:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WxMemberCreditActiveF generated by hbm2java
 */
@Entity
@Table(name = "wx_member_credit_active_f")
public class WxMemberCreditActiveF implements java.io.Serializable {

	private String memberCreditGuid;
	private String actName;
	private String actDesc;
	private String actImage;
	private String actContent;
	private Integer actType;
	private Integer actType2;
	private Integer status;
	private String startOn;
	private String endOn;
	private String gzhHash;
	private Integer source;
	private String line;
	private Integer maxNum;
	private Integer childMax;
	private String createdBy;
	private String createdOn;
	private String modifyBy;
	private String modifyOn;
	private String publishOn;
	private String publishBy;
	private String carTypeGuid;
	private String carTypeTitle;
	private Integer delFlag;
	private Integer creditFlag;
	private String dealerCode;
	private Integer actCredit;
	private String ticket;
	private Integer sceneId;
	private Integer updateCount;

	public WxMemberCreditActiveF() {
	}

	public WxMemberCreditActiveF(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	public WxMemberCreditActiveF(String memberCreditGuid, String actName,
			String actDesc, String actImage, String actContent,
			Integer actType, Integer actType2, Integer status, String startOn,
			String endOn, String gzhHash, Integer source, String line,
			Integer maxNum, Integer childMax, String createdBy,
			String createdOn, String modifyBy, String modifyOn,
			String publishOn, String publishBy, String carTypeGuid,
			String carTypeTitle, Integer delFlag, Integer creditFlag,
			String dealerCode, Integer actCredit, String ticket,
			Integer sceneId, Integer updateCount) {
		this.memberCreditGuid = memberCreditGuid;
		this.actName = actName;
		this.actDesc = actDesc;
		this.actImage = actImage;
		this.actContent = actContent;
		this.actType = actType;
		this.actType2 = actType2;
		this.status = status;
		this.startOn = startOn;
		this.endOn = endOn;
		this.gzhHash = gzhHash;
		this.source = source;
		this.line = line;
		this.maxNum = maxNum;
		this.childMax = childMax;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.publishOn = publishOn;
		this.publishBy = publishBy;
		this.carTypeGuid = carTypeGuid;
		this.carTypeTitle = carTypeTitle;
		this.delFlag = delFlag;
		this.creditFlag = creditFlag;
		this.dealerCode = dealerCode;
		this.actCredit = actCredit;
		this.ticket = ticket;
		this.sceneId = sceneId;
		this.updateCount = updateCount;
	}

	@Id
	@Column(name = "member_credit_guid", unique = true, nullable = false, length = 36)
	public String getMemberCreditGuid() {
		return this.memberCreditGuid;
	}

	public void setMemberCreditGuid(String memberCreditGuid) {
		this.memberCreditGuid = memberCreditGuid;
	}

	@Column(name = "act_name", length = 100)
	public String getActName() {
		return this.actName;
	}

	public void setActName(String actName) {
		this.actName = actName;
	}

	@Column(name = "act_desc")
	public String getActDesc() {
		return this.actDesc;
	}

	public void setActDesc(String actDesc) {
		this.actDesc = actDesc;
	}

	@Column(name = "act_image")
	public String getActImage() {
		return this.actImage;
	}

	public void setActImage(String actImage) {
		this.actImage = actImage;
	}

	@Column(name = "act_content", length = 65535)
	public String getActContent() {
		return this.actContent;
	}

	public void setActContent(String actContent) {
		this.actContent = actContent;
	}

	@Column(name = "act_type")
	public Integer getActType() {
		return this.actType;
	}

	public void setActType(Integer actType) {
		this.actType = actType;
	}

	@Column(name = "act_type2")
	public Integer getActType2() {
		return this.actType2;
	}

	public void setActType2(Integer actType2) {
		this.actType2 = actType2;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "start_on", length = 25)
	public String getStartOn() {
		return this.startOn;
	}

	public void setStartOn(String startOn) {
		this.startOn = startOn;
	}

	@Column(name = "end_on", length = 25)
	public String getEndOn() {
		return this.endOn;
	}

	public void setEndOn(String endOn) {
		this.endOn = endOn;
	}

	@Column(name = "gzh_hash", length = 36)
	public String getGzhHash() {
		return this.gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "source")
	public Integer getSource() {
		return this.source;
	}

	public void setSource(Integer source) {
		this.source = source;
	}

	@Column(name = "line", length = 1000)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "max_num")
	public Integer getMaxNum() {
		return this.maxNum;
	}

	public void setMaxNum(Integer maxNum) {
		this.maxNum = maxNum;
	}

	@Column(name = "child_max")
	public Integer getChildMax() {
		return this.childMax;
	}

	public void setChildMax(Integer childMax) {
		this.childMax = childMax;
	}

	@Column(name = "created_by", length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by", length = 36)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modify_on", length = 25)
	public String getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(String modifyOn) {
		this.modifyOn = modifyOn;
	}

	@Column(name = "publish_on", length = 25)
	public String getPublishOn() {
		return this.publishOn;
	}

	public void setPublishOn(String publishOn) {
		this.publishOn = publishOn;
	}

	@Column(name = "publish_by", length = 36)
	public String getPublishBy() {
		return this.publishBy;
	}

	public void setPublishBy(String publishBy) {
		this.publishBy = publishBy;
	}

	@Column(name = "car_type_guid", length = 36)
	public String getCarTypeGuid() {
		return this.carTypeGuid;
	}

	public void setCarTypeGuid(String carTypeGuid) {
		this.carTypeGuid = carTypeGuid;
	}

	@Column(name = "car_type_title", length = 200)
	public String getCarTypeTitle() {
		return this.carTypeTitle;
	}

	public void setCarTypeTitle(String carTypeTitle) {
		this.carTypeTitle = carTypeTitle;
	}

	@Column(name = "del_flag")
	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "credit_Flag")
	public Integer getCreditFlag() {
		return this.creditFlag;
	}

	public void setCreditFlag(Integer creditFlag) {
		this.creditFlag = creditFlag;
	}

	@Column(name = "dealer_code", length = 5)
	public String getDealerCode() {
		return this.dealerCode;
	}

	public void setDealerCode(String dealerCode) {
		this.dealerCode = dealerCode;
	}

	@Column(name = "act_credit")
	public Integer getActCredit() {
		return this.actCredit;
	}

	public void setActCredit(Integer actCredit) {
		this.actCredit = actCredit;
	}

	@Column(name = "ticket", length = 200)
	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	@Column(name = "scene_id")
	public Integer getSceneId() {
		return this.sceneId;
	}

	public void setSceneId(Integer sceneId) {
		this.sceneId = sceneId;
	}

	@Column(name = "update_count")
	public Integer getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

}
