package com.tlan.common.model.creditactive;

// Generated 2014-7-8 9:42:25 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WxMemberCreditManageF generated by hbm2java
 */
@Entity
@Table(name = "wx_member_credit_manage_f")
public class WxMemberCreditManageF implements java.io.Serializable {

	private String memberActGuid;
	private String gzhHash;
	private String memberGuid;
	private String actGuid;
	private Integer delFlag;
	private Integer updateCount;
	private String createdOn;
	private String createdBy;
	private String modifyOn;
	private String modifyBy;
	private String t1;
	private String t2;
	private String t3;
	private String t4;
	private String t5;
	private String t6;
	private String t7;
	private String t8;
	private String t9;
	private String t10;

	public WxMemberCreditManageF() {
	}

	public WxMemberCreditManageF(String memberActGuid, String gzhHash,
			String memberGuid, String actGuid) {
		this.memberActGuid = memberActGuid;
		this.gzhHash = gzhHash;
		this.memberGuid = memberGuid;
		this.actGuid = actGuid;
	}

	public WxMemberCreditManageF(String memberActGuid, String gzhHash,
			String memberGuid, String actGuid, Integer delFlag,
			Integer updateCount, String createdOn, String createdBy,
			String modifyOn, String modifyBy, String t1, String t2, String t3,
			String t4, String t5, String t6, String t7, String t8, String t9,
			String t10) {
		this.memberActGuid = memberActGuid;
		this.gzhHash = gzhHash;
		this.memberGuid = memberGuid;
		this.actGuid = actGuid;
		this.delFlag = delFlag;
		this.updateCount = updateCount;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifyOn = modifyOn;
		this.modifyBy = modifyBy;
		this.t1 = t1;
		this.t2 = t2;
		this.t3 = t3;
		this.t4 = t4;
		this.t5 = t5;
		this.t6 = t6;
		this.t7 = t7;
		this.t8 = t8;
		this.t9 = t9;
		this.t10 = t10;
	}

	@Id
	@Column(name = "member_act_guid", unique = true, nullable = false, length = 36)
	public String getMemberActGuid() {
		return this.memberActGuid;
	}

	public void setMemberActGuid(String memberActGuid) {
		this.memberActGuid = memberActGuid;
	}

	@Column(name = "gzh_hash", nullable = false, length = 36)
	public String getGzhHash() {
		return this.gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "member_guid", nullable = false, length = 36)
	public String getMemberGuid() {
		return this.memberGuid;
	}

	public void setMemberGuid(String memberGuid) {
		this.memberGuid = memberGuid;
	}

	@Column(name = "act_guid", nullable = false, length = 36)
	public String getActGuid() {
		return this.actGuid;
	}

	public void setActGuid(String actGuid) {
		this.actGuid = actGuid;
	}

	@Column(name = "del_flag")
	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "update_count")
	public Integer getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "modify_on", length = 25)
	public String getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(String modifyOn) {
		this.modifyOn = modifyOn;
	}

	@Column(name = "modify_by", length = 36)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "t1")
	public String getT1() {
		return this.t1;
	}

	public void setT1(String t1) {
		this.t1 = t1;
	}

	@Column(name = "t2")
	public String getT2() {
		return this.t2;
	}

	public void setT2(String t2) {
		this.t2 = t2;
	}

	@Column(name = "t3")
	public String getT3() {
		return this.t3;
	}

	public void setT3(String t3) {
		this.t3 = t3;
	}

	@Column(name = "t4")
	public String getT4() {
		return this.t4;
	}

	public void setT4(String t4) {
		this.t4 = t4;
	}

	@Column(name = "t5")
	public String getT5() {
		return this.t5;
	}

	public void setT5(String t5) {
		this.t5 = t5;
	}

	@Column(name = "t6")
	public String getT6() {
		return this.t6;
	}

	public void setT6(String t6) {
		this.t6 = t6;
	}

	@Column(name = "t7")
	public String getT7() {
		return this.t7;
	}

	public void setT7(String t7) {
		this.t7 = t7;
	}

	@Column(name = "t8")
	public String getT8() {
		return this.t8;
	}

	public void setT8(String t8) {
		this.t8 = t8;
	}

	@Column(name = "t9")
	public String getT9() {
		return this.t9;
	}

	public void setT9(String t9) {
		this.t9 = t9;
	}

	@Column(name = "t10")
	public String getT10() {
		return this.t10;
	}

	public void setT10(String t10) {
		this.t10 = t10;
	}

}
