package com.tlan.common.model.creditactive;

// Generated 2014-6-25 16:54:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxOrderManageViewId generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_order_manage_view")
public class WxOrderManageView implements java.io.Serializable {

	private String productLogo;
	private Integer productCredit;
	private String productOrderGuid;
	private String orderStatusGuid;
	private String orderStatusName;
	private String productOrderDate;
	private String productOrderNum;
	private int productCount;
	private String openId;
	private String gzhHash;
	private String userLocationName;
	private String userLocationProvice;
	private String userLocationCity;
	private String userLocationDistrict;
	private String userLocationStreet;
	private String userLocationPhone;
	private String productName;
	private String productGuid;
	private String userGuid;
	private String userLocationGuid;

	public WxOrderManageView() {
	}

	public WxOrderManageView(String productOrderGuid, String orderStatusGuid,
			String productOrderDate, String productOrderNum, int productCount,
			String productGuid, String userGuid, String userLocationGuid) {
		this.productOrderGuid = productOrderGuid;
		this.orderStatusGuid = orderStatusGuid;
		this.productOrderDate = productOrderDate;
		this.productOrderNum = productOrderNum;
		this.productCount = productCount;
		this.productGuid = productGuid;
		this.userGuid = userGuid;
		this.userLocationGuid = userLocationGuid;
	}

	public WxOrderManageView(String productLogo, Integer productCredit,
			String productOrderGuid, String orderStatusGuid,
			String orderStatusName, String productOrderDate,
			String productOrderNum, int productCount, String openId,
			String gzhHash, String userLocationName,
			String userLocationProvice, String userLocationCity,
			String userLocationDistrict, String userLocationStreet,
			String userLocationPhone, String productName, String productGuid,
			String userGuid, String userLocationGuid) {
		this.productLogo = productLogo;
		this.productCredit = productCredit;
		this.productOrderGuid = productOrderGuid;
		this.orderStatusGuid = orderStatusGuid;
		this.orderStatusName = orderStatusName;
		this.productOrderDate = productOrderDate;
		this.productOrderNum = productOrderNum;
		this.productCount = productCount;
		this.openId = openId;
		this.gzhHash = gzhHash;
		this.userLocationName = userLocationName;
		this.userLocationProvice = userLocationProvice;
		this.userLocationCity = userLocationCity;
		this.userLocationDistrict = userLocationDistrict;
		this.userLocationStreet = userLocationStreet;
		this.userLocationPhone = userLocationPhone;
		this.productName = productName;
		this.productGuid = productGuid;
		this.userGuid = userGuid;
		this.userLocationGuid = userLocationGuid;
	}

	@Column(name = "product_logo", length = 200)
	public String getProductLogo() {
		return this.productLogo;
	}

	public void setProductLogo(String productLogo) {
		this.productLogo = productLogo;
	}

	@Column(name = "product_credit")
	public Integer getProductCredit() {
		return this.productCredit;
	}

	public void setProductCredit(Integer productCredit) {
		this.productCredit = productCredit;
	}
	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "product_order_guid", nullable = false, length = 36)
	public String getProductOrderGuid() {
		return this.productOrderGuid;
	}

	public void setProductOrderGuid(String productOrderGuid) {
		this.productOrderGuid = productOrderGuid;
	}

	@Column(name = "order_status_guid", nullable = false, length = 36)
	public String getOrderStatusGuid() {
		return this.orderStatusGuid;
	}

	public void setOrderStatusGuid(String orderStatusGuid) {
		this.orderStatusGuid = orderStatusGuid;
	}

	@Column(name = "order_status_name", length = 50)
	public String getOrderStatusName() {
		return this.orderStatusName;
	}

	public void setOrderStatusName(String orderStatusName) {
		this.orderStatusName = orderStatusName;
	}

	@Column(name = "product_order_date", nullable = false, length = 25)
	public String getProductOrderDate() {
		return this.productOrderDate;
	}

	public void setProductOrderDate(String productOrderDate) {
		this.productOrderDate = productOrderDate;
	}

	@Column(name = "product_order_num", nullable = false, length = 36)
	public String getProductOrderNum() {
		return this.productOrderNum;
	}

	public void setProductOrderNum(String productOrderNum) {
		this.productOrderNum = productOrderNum;
	}

	@Column(name = "product_count", nullable = false)
	public int getProductCount() {
		return this.productCount;
	}

	public void setProductCount(int productCount) {
		this.productCount = productCount;
	}

	@Column(name = "open_id", length = 50)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "gzh_hash", length = 36)
	public String getGzhHash() {
		return this.gzhHash;
	}

	public void setGzhHash(String gzhHash) {
		this.gzhHash = gzhHash;
	}

	@Column(name = "user_location_name", length = 36)
	public String getUserLocationName() {
		return this.userLocationName;
	}

	public void setUserLocationName(String userLocationName) {
		this.userLocationName = userLocationName;
	}

	@Column(name = "user_location_provice", length = 36)
	public String getUserLocationProvice() {
		return this.userLocationProvice;
	}

	public void setUserLocationProvice(String userLocationProvice) {
		this.userLocationProvice = userLocationProvice;
	}

	@Column(name = "user_location_city", length = 36)
	public String getUserLocationCity() {
		return this.userLocationCity;
	}

	public void setUserLocationCity(String userLocationCity) {
		this.userLocationCity = userLocationCity;
	}

	@Column(name = "user_location_district", length = 36)
	public String getUserLocationDistrict() {
		return this.userLocationDistrict;
	}

	public void setUserLocationDistrict(String userLocationDistrict) {
		this.userLocationDistrict = userLocationDistrict;
	}

	@Column(name = "user_location_street", length = 36)
	public String getUserLocationStreet() {
		return this.userLocationStreet;
	}

	public void setUserLocationStreet(String userLocationStreet) {
		this.userLocationStreet = userLocationStreet;
	}

	@Column(name = "user_location_phone", length = 36)
	public String getUserLocationPhone() {
		return this.userLocationPhone;
	}

	public void setUserLocationPhone(String userLocationPhone) {
		this.userLocationPhone = userLocationPhone;
	}

	@Column(name = "product_name", length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_guid", nullable = false, length = 36)
	public String getProductGuid() {
		return this.productGuid;
	}

	public void setProductGuid(String productGuid) {
		this.productGuid = productGuid;
	}

	@Column(name = "user_guid", nullable = false, length = 36)
	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	@Column(name = "user_location_guid", nullable = false, length = 36)
	public String getUserLocationGuid() {
		return this.userLocationGuid;
	}

	public void setUserLocationGuid(String userLocationGuid) {
		this.userLocationGuid = userLocationGuid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WxOrderManageView))
			return false;
		WxOrderManageView castOther = (WxOrderManageView) other;

		return ((this.getProductLogo() == castOther.getProductLogo()) || (this
				.getProductLogo() != null && castOther.getProductLogo() != null && this
				.getProductLogo().equals(castOther.getProductLogo())))
				&& ((this.getProductCredit() == castOther.getProductCredit()) || (this
						.getProductCredit() != null
						&& castOther.getProductCredit() != null && this
						.getProductCredit()
						.equals(castOther.getProductCredit())))
				&& ((this.getProductOrderGuid() == castOther
						.getProductOrderGuid()) || (this.getProductOrderGuid() != null
						&& castOther.getProductOrderGuid() != null && this
						.getProductOrderGuid().equals(
								castOther.getProductOrderGuid())))
				&& ((this.getOrderStatusGuid() == castOther
						.getOrderStatusGuid()) || (this.getOrderStatusGuid() != null
						&& castOther.getOrderStatusGuid() != null && this
						.getOrderStatusGuid().equals(
								castOther.getOrderStatusGuid())))
				&& ((this.getOrderStatusName() == castOther
						.getOrderStatusName()) || (this.getOrderStatusName() != null
						&& castOther.getOrderStatusName() != null && this
						.getOrderStatusName().equals(
								castOther.getOrderStatusName())))
				&& ((this.getProductOrderDate() == castOther
						.getProductOrderDate()) || (this.getProductOrderDate() != null
						&& castOther.getProductOrderDate() != null && this
						.getProductOrderDate().equals(
								castOther.getProductOrderDate())))
				&& ((this.getProductOrderNum() == castOther
						.getProductOrderNum()) || (this.getProductOrderNum() != null
						&& castOther.getProductOrderNum() != null && this
						.getProductOrderNum().equals(
								castOther.getProductOrderNum())))
				&& (this.getProductCount() == castOther.getProductCount())
				&& ((this.getOpenId() == castOther.getOpenId()) || (this
						.getOpenId() != null && castOther.getOpenId() != null && this
						.getOpenId().equals(castOther.getOpenId())))
				&& ((this.getGzhHash() == castOther.getGzhHash()) || (this
						.getGzhHash() != null && castOther.getGzhHash() != null && this
						.getGzhHash().equals(castOther.getGzhHash())))
				&& ((this.getUserLocationName() == castOther
						.getUserLocationName()) || (this.getUserLocationName() != null
						&& castOther.getUserLocationName() != null && this
						.getUserLocationName().equals(
								castOther.getUserLocationName())))
				&& ((this.getUserLocationProvice() == castOther
						.getUserLocationProvice()) || (this
						.getUserLocationProvice() != null
						&& castOther.getUserLocationProvice() != null && this
						.getUserLocationProvice().equals(
								castOther.getUserLocationProvice())))
				&& ((this.getUserLocationCity() == castOther
						.getUserLocationCity()) || (this.getUserLocationCity() != null
						&& castOther.getUserLocationCity() != null && this
						.getUserLocationCity().equals(
								castOther.getUserLocationCity())))
				&& ((this.getUserLocationDistrict() == castOther
						.getUserLocationDistrict()) || (this
						.getUserLocationDistrict() != null
						&& castOther.getUserLocationDistrict() != null && this
						.getUserLocationDistrict().equals(
								castOther.getUserLocationDistrict())))
				&& ((this.getUserLocationStreet() == castOther
						.getUserLocationStreet()) || (this
						.getUserLocationStreet() != null
						&& castOther.getUserLocationStreet() != null && this
						.getUserLocationStreet().equals(
								castOther.getUserLocationStreet())))
				&& ((this.getUserLocationPhone() == castOther
						.getUserLocationPhone()) || (this
						.getUserLocationPhone() != null
						&& castOther.getUserLocationPhone() != null && this
						.getUserLocationPhone().equals(
								castOther.getUserLocationPhone())))
				&& ((this.getProductName() == castOther.getProductName()) || (this
						.getProductName() != null
						&& castOther.getProductName() != null && this
						.getProductName().equals(castOther.getProductName())))
				&& ((this.getProductGuid() == castOther.getProductGuid()) || (this
						.getProductGuid() != null
						&& castOther.getProductGuid() != null && this
						.getProductGuid().equals(castOther.getProductGuid())))
				&& ((this.getUserGuid() == castOther.getUserGuid()) || (this
						.getUserGuid() != null
						&& castOther.getUserGuid() != null && this
						.getUserGuid().equals(castOther.getUserGuid())))
				&& ((this.getUserLocationGuid() == castOther
						.getUserLocationGuid()) || (this.getUserLocationGuid() != null
						&& castOther.getUserLocationGuid() != null && this
						.getUserLocationGuid().equals(
								castOther.getUserLocationGuid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProductLogo() == null ? 0 : this.getProductLogo()
						.hashCode());
		result = 37
				* result
				+ (getProductCredit() == null ? 0 : this.getProductCredit()
						.hashCode());
		result = 37
				* result
				+ (getProductOrderGuid() == null ? 0 : this
						.getProductOrderGuid().hashCode());
		result = 37
				* result
				+ (getOrderStatusGuid() == null ? 0 : this.getOrderStatusGuid()
						.hashCode());
		result = 37
				* result
				+ (getOrderStatusName() == null ? 0 : this.getOrderStatusName()
						.hashCode());
		result = 37
				* result
				+ (getProductOrderDate() == null ? 0 : this
						.getProductOrderDate().hashCode());
		result = 37
				* result
				+ (getProductOrderNum() == null ? 0 : this.getProductOrderNum()
						.hashCode());
		result = 37 * result + this.getProductCount();
		result = 37 * result
				+ (getOpenId() == null ? 0 : this.getOpenId().hashCode());
		result = 37 * result
				+ (getGzhHash() == null ? 0 : this.getGzhHash().hashCode());
		result = 37
				* result
				+ (getUserLocationName() == null ? 0 : this
						.getUserLocationName().hashCode());
		result = 37
				* result
				+ (getUserLocationProvice() == null ? 0 : this
						.getUserLocationProvice().hashCode());
		result = 37
				* result
				+ (getUserLocationCity() == null ? 0 : this
						.getUserLocationCity().hashCode());
		result = 37
				* result
				+ (getUserLocationDistrict() == null ? 0 : this
						.getUserLocationDistrict().hashCode());
		result = 37
				* result
				+ (getUserLocationStreet() == null ? 0 : this
						.getUserLocationStreet().hashCode());
		result = 37
				* result
				+ (getUserLocationPhone() == null ? 0 : this
						.getUserLocationPhone().hashCode());
		result = 37
				* result
				+ (getProductName() == null ? 0 : this.getProductName()
						.hashCode());
		result = 37
				* result
				+ (getProductGuid() == null ? 0 : this.getProductGuid()
						.hashCode());
		result = 37 * result
				+ (getUserGuid() == null ? 0 : this.getUserGuid().hashCode());
		result = 37
				* result
				+ (getUserLocationGuid() == null ? 0 : this
						.getUserLocationGuid().hashCode());
		return result;
	}

}
