package com.tlan.common.model.creditactive;

// Generated 2014-6-18 15:47:34 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxProductListViewId generated by hbm2java
 */
@Embeddable
@Entity
@Table(name = "wx_product_list_view")
public class WxProductListView implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8812599802743560250L;
	private String productGuid;
	private String productName;
	private String productKey;
	private String productPrice;
	private String productDate;
	private String productLogo;
	private String productDoc;
	private String productSpec;
	private Integer productCredit;
	private String productTypeId;
	private Integer productStock;
	private Integer status;
	private String publishOn;
	private String publishBy;
	private String createdBy;
	private String createdOn;
	private String modifyBy;
	private String modifyOn;
	private Integer delFlag;
	private Integer updateCount;
	private String productTypeName;

	public WxProductListView() {
	}

	public WxProductListView(String productGuid) {
		this.productGuid = productGuid;
	}

	public WxProductListView(String productGuid, String productName,
			String productKey, String productPrice, String productDate,
			String productLogo, String productDoc, String productSpec,
			Integer productCredit, String productTypeId, Integer productStock,
			Integer status, String publishOn, String publishBy,
			String createdBy, String createdOn, String modifyBy,
			String modifyOn, Integer delFlag, Integer updateCount,
			String productTypeName) {
		this.productGuid = productGuid;
		this.productName = productName;
		this.productKey = productKey;
		this.productPrice = productPrice;
		this.productDate = productDate;
		this.productLogo = productLogo;
		this.productDoc = productDoc;
		this.productSpec = productSpec;
		this.productCredit = productCredit;
		this.productTypeId = productTypeId;
		this.productStock = productStock;
		this.status = status;
		this.publishOn = publishOn;
		this.publishBy = publishBy;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.delFlag = delFlag;
		this.updateCount = updateCount;
		this.productTypeName = productTypeName;
	}

	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "product_guid", nullable = false, length = 36)
	public String getProductGuid() {
		return this.productGuid;
	}

	public void setProductGuid(String productGuid) {
		this.productGuid = productGuid;
	}

	@Column(name = "product_name", length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_key", length = 100)
	public String getProductKey() {
		return this.productKey;
	}

	public void setProductKey(String productKey) {
		this.productKey = productKey;
	}

	@Column(name = "product_price", length = 100)
	public String getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(String productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "product_date", length = 25)
	public String getProductDate() {
		return this.productDate;
	}

	public void setProductDate(String productDate) {
		this.productDate = productDate;
	}

	@Column(name = "product_logo", length = 200)
	public String getProductLogo() {
		return this.productLogo;
	}

	public void setProductLogo(String productLogo) {
		this.productLogo = productLogo;
	}

	@Column(name = "product_doc", length = 65535)
	public String getProductDoc() {
		return this.productDoc;
	}

	public void setProductDoc(String productDoc) {
		this.productDoc = productDoc;
	}

	@Column(name = "product_spec", length = 65535)
	public String getProductSpec() {
		return this.productSpec;
	}

	public void setProductSpec(String productSpec) {
		this.productSpec = productSpec;
	}

	@Column(name = "product_credit")
	public Integer getProductCredit() {
		return this.productCredit;
	}

	public void setProductCredit(Integer productCredit) {
		this.productCredit = productCredit;
	}

	@Column(name = "product_type_id", length = 36)
	public String getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(String productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "product_stock")
	public Integer getProductStock() {
		return this.productStock;
	}

	public void setProductStock(Integer productStock) {
		this.productStock = productStock;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "publish_on", length = 25)
	public String getPublishOn() {
		return this.publishOn;
	}

	public void setPublishOn(String publishOn) {
		this.publishOn = publishOn;
	}

	@Column(name = "publish_by", length = 36)
	public String getPublishBy() {
		return this.publishBy;
	}

	public void setPublishBy(String publishBy) {
		this.publishBy = publishBy;
	}

	@Column(name = "created_by", length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by", length = 36)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modify_on", length = 25)
	public String getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(String modifyOn) {
		this.modifyOn = modifyOn;
	}

	@Column(name = "del_flag")
	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "update_count")
	public Integer getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

	@Column(name = "product_type_name", length = 50)
	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WxProductListView))
			return false;
		WxProductListView castOther = (WxProductListView) other;

		return ((this.getProductGuid() == castOther.getProductGuid()) || (this
				.getProductGuid() != null && castOther.getProductGuid() != null && this
				.getProductGuid().equals(castOther.getProductGuid())))
				&& ((this.getProductName() == castOther.getProductName()) || (this
						.getProductName() != null
						&& castOther.getProductName() != null && this
						.getProductName().equals(castOther.getProductName())))
				&& ((this.getProductKey() == castOther.getProductKey()) || (this
						.getProductKey() != null
						&& castOther.getProductKey() != null && this
						.getProductKey().equals(castOther.getProductKey())))
				&& ((this.getProductPrice() == castOther.getProductPrice()) || (this
						.getProductPrice() != null
						&& castOther.getProductPrice() != null && this
						.getProductPrice().equals(castOther.getProductPrice())))
				&& ((this.getProductDate() == castOther.getProductDate()) || (this
						.getProductDate() != null
						&& castOther.getProductDate() != null && this
						.getProductDate().equals(castOther.getProductDate())))
				&& ((this.getProductLogo() == castOther.getProductLogo()) || (this
						.getProductLogo() != null
						&& castOther.getProductLogo() != null && this
						.getProductLogo().equals(castOther.getProductLogo())))
				&& ((this.getProductDoc() == castOther.getProductDoc()) || (this
						.getProductDoc() != null
						&& castOther.getProductDoc() != null && this
						.getProductDoc().equals(castOther.getProductDoc())))
				&& ((this.getProductSpec() == castOther.getProductSpec()) || (this
						.getProductSpec() != null
						&& castOther.getProductSpec() != null && this
						.getProductSpec().equals(castOther.getProductSpec())))
				&& ((this.getProductCredit() == castOther.getProductCredit()) || (this
						.getProductCredit() != null
						&& castOther.getProductCredit() != null && this
						.getProductCredit()
						.equals(castOther.getProductCredit())))
				&& ((this.getProductTypeId() == castOther.getProductTypeId()) || (this
						.getProductTypeId() != null
						&& castOther.getProductTypeId() != null && this
						.getProductTypeId()
						.equals(castOther.getProductTypeId())))
				&& ((this.getProductStock() == castOther.getProductStock()) || (this
						.getProductStock() != null
						&& castOther.getProductStock() != null && this
						.getProductStock().equals(castOther.getProductStock())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getPublishOn() == castOther.getPublishOn()) || (this
						.getPublishOn() != null
						&& castOther.getPublishOn() != null && this
						.getPublishOn().equals(castOther.getPublishOn())))
				&& ((this.getPublishBy() == castOther.getPublishBy()) || (this
						.getPublishBy() != null
						&& castOther.getPublishBy() != null && this
						.getPublishBy().equals(castOther.getPublishBy())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this
						.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this
						.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getModifyBy() == castOther.getModifyBy()) || (this
						.getModifyBy() != null
						&& castOther.getModifyBy() != null && this
						.getModifyBy().equals(castOther.getModifyBy())))
				&& ((this.getModifyOn() == castOther.getModifyOn()) || (this
						.getModifyOn() != null
						&& castOther.getModifyOn() != null && this
						.getModifyOn().equals(castOther.getModifyOn())))
				&& ((this.getDelFlag() == castOther.getDelFlag()) || (this
						.getDelFlag() != null && castOther.getDelFlag() != null && this
						.getDelFlag().equals(castOther.getDelFlag())))
				&& ((this.getUpdateCount() == castOther.getUpdateCount()) || (this
						.getUpdateCount() != null
						&& castOther.getUpdateCount() != null && this
						.getUpdateCount().equals(castOther.getUpdateCount())))
				&& ((this.getProductTypeName() == castOther
						.getProductTypeName()) || (this.getProductTypeName() != null
						&& castOther.getProductTypeName() != null && this
						.getProductTypeName().equals(
								castOther.getProductTypeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProductGuid() == null ? 0 : this.getProductGuid()
						.hashCode());
		result = 37
				* result
				+ (getProductName() == null ? 0 : this.getProductName()
						.hashCode());
		result = 37
				* result
				+ (getProductKey() == null ? 0 : this.getProductKey()
						.hashCode());
		result = 37
				* result
				+ (getProductPrice() == null ? 0 : this.getProductPrice()
						.hashCode());
		result = 37
				* result
				+ (getProductDate() == null ? 0 : this.getProductDate()
						.hashCode());
		result = 37
				* result
				+ (getProductLogo() == null ? 0 : this.getProductLogo()
						.hashCode());
		result = 37
				* result
				+ (getProductDoc() == null ? 0 : this.getProductDoc()
						.hashCode());
		result = 37
				* result
				+ (getProductSpec() == null ? 0 : this.getProductSpec()
						.hashCode());
		result = 37
				* result
				+ (getProductCredit() == null ? 0 : this.getProductCredit()
						.hashCode());
		result = 37
				* result
				+ (getProductTypeId() == null ? 0 : this.getProductTypeId()
						.hashCode());
		result = 37
				* result
				+ (getProductStock() == null ? 0 : this.getProductStock()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getPublishOn() == null ? 0 : this.getPublishOn().hashCode());
		result = 37 * result
				+ (getPublishBy() == null ? 0 : this.getPublishBy().hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result
				+ (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result
				+ (getModifyBy() == null ? 0 : this.getModifyBy().hashCode());
		result = 37 * result
				+ (getModifyOn() == null ? 0 : this.getModifyOn().hashCode());
		result = 37 * result
				+ (getDelFlag() == null ? 0 : this.getDelFlag().hashCode());
		result = 37
				* result
				+ (getUpdateCount() == null ? 0 : this.getUpdateCount()
						.hashCode());
		result = 37
				* result
				+ (getProductTypeName() == null ? 0 : this.getProductTypeName()
						.hashCode());
		return result;
	}

}
