package com.tlan.common.model.creditactive;

// Generated 2014-6-17 14:39:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * WxProductTypeM generated by hbm2java
 */
@Entity
@Table(name = "wx_product_type_m")
public class WxProductTypeM implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 578507765536150821L;
	private String productTypeGuid;
	private String productName;
	private String createdBy;
	private String createdOn;
	private String modifyBy;
	private String modifyOn;
	private Integer delFlag;
	private Integer updateCount;

	public WxProductTypeM() {
	}

	public WxProductTypeM(String productTypeGuid) {
		this.productTypeGuid = productTypeGuid;
	}

	public WxProductTypeM(String productTypeGuid, String productName,
			String createdBy, String createdOn, String modifyBy,
			String modifyOn, Integer delFlag, Integer updateCount) {
		this.productTypeGuid = productTypeGuid;
		this.productName = productName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.modifyBy = modifyBy;
		this.modifyOn = modifyOn;
		this.delFlag = delFlag;
		this.updateCount = updateCount;
	}

	@Id
	@GeneratedValue(generator = "custom-id")
	@GenericGenerator(name = "custom-id", strategy = "assigned")
	@Column(name = "product_type_guid", unique = true, nullable = false, length = 36)
	public String getProductTypeGuid() {
		return this.productTypeGuid;
	}

	public void setProductTypeGuid(String productTypeGuid) {
		this.productTypeGuid = productTypeGuid;
	}

	@Column(name = "product_name", length = 50)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "created_by", length = 36)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "created_on", length = 25)
	public String getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "modify_by", length = 36)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Column(name = "modify_on", length = 25)
	public String getModifyOn() {
		return this.modifyOn;
	}

	public void setModifyOn(String modifyOn) {
		this.modifyOn = modifyOn;
	}

	@Column(name = "del_flag")
	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "update_count")
	public Integer getUpdateCount() {
		return this.updateCount;
	}

	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

}
